关于合作

* 起因
  最近在维护一个有意思的项目(去年10月-现在),对于作为学生的我来说每周也能带来一笔可观的收入.闲聊时,我吐槽了项目继续扩大规模(多开发一个软件,功能类似,用户群不同),精力不足的事.朋友A君表示有兴趣加入.平时了解到A君是一个能力和责任心比较出色的同学,当时不假思索地答应了.于是口头上开始了合作,这也为后来一系列不愉快的事情打下了基础.

* 任务分配
  目前已经完成的软件已经相对稳定,技术架构,代码,用户都已经合作默契,任务分工有条不紊地推进.对于自身来说,维护也很轻松,如果需求改动不大,每周花2-3天就可以完成任务;需求改动较大的时候,会花费比较多的时间,不仅仅是代码量较大,知识和技术要求也比较高.

  新开发的软件可以在现有的基础上开发,重用已经完成的基础设施. 但是之前的成果是半年积蓄而成,虽然新的部分有现有的基础,新软件到盈利还需要1-2个月时间(当时按照我自身能力对进度的预估).

  当然,如果没有A君的加入,我短时间不会考虑扩展,而是继续稳定已经完成的软件.A君加入后,一个自然的想法是希望A君维护新开发的软件,建立新的用户群体.因为新软件不涉及到业务流程,主要是一些界面开发和服务器交互,相对来说起始门槛更低,对突发状况的处理也没有很急迫的要求(老软件更新好了,新软件底层也自然更新好了).事实上也是这样做的.

  花了一点时间做技术选型,然后让朋友和A君沟通帮助推广.以及现有部分的代码.开干之前和A君强调了一下项目风险,并不一定能够成功,并且CODING能力要求较高,必须要针对突发情况做出快速反应(有时候可能是1-2分钟,有时候是1-2天必须处理好问题),否则用户会快速丢失(1-2个问题没处理好,会丢失一半的用户,如果连续几次处理不好,基本可以宣告失败).还有一点是软件需要持续更新,也就是说写好的东西随时可能因为需求的改变(需求一直在变动,这是外部因素,并非客户要求)而改变或者完全重新推翻,也就是说我们赚的不是软件钱,而是维护费,软件一周不跟上需求变化,这一期就基本报废.

* 合作第一周
   新软件开发的主要工作是在老软件的业务逻辑上加一层界面,并且提供授权的功能(客户端\服务器),当然会有一些适配的问题需要处理. 老软件已经完成工作包括:整套业务逻辑,一个高性能的中心服务器以及其管理框架,各类基础组件,如验证码识别,并发控制,自动更新,Web通讯,各类Cache,服务器交互,完善的日志以及异常处理框架.

   A君初次加入,对业务技术有一段适应期,刚开始开发速度较慢.新软件从最初的2周延长到2个月初次上线.

   第一周,A君处于学习摸索阶段,每天在实验室工作到很晚,不过新软件依旧没有太大起色. 但是老软件持续盈利, A君提出自己作为参与者要求分红.

   到这里,我有2个选择:

   1. A君不应该在老软件项目上分红. 因为老软件依旧是我独立维护, A君参与并没有对老软件现有的生态造成任何影响, 对盈利也没有任何贡献. 对于我来说, 我的工作量和工作模式并不比以前少,相反因为新软件的开发,我在更新底层组件的时候需要考虑新软件的兼容性, 并分少量心到新软件开发遇到的各种问题上.
   2. A君应该分红. 因为他是合作者, 作为合作者虽然加入较晚, 贡献较少, 考虑到后来的贡献, 作为合作者的身份应该参与新老软件总收入的分红.

   这里的核心是,[后来的贡献],如果有理由相信,合作能够让双方受益,即现在我分出去的红,以后能够得到至少等量的回报,我想我应该选择方案2. 否则,与人合作,工作量增加,利润减少,从一开始就没有合作的必要. 另一个相对保守的方式是方案1. 方案1保证按劳分配,即谁[已经]完成了多少工作,已经完成的工作对最后盈利造成了多大的[因果关系],就应该得到多少分红.

   最终我的选择是,在老软件上提供一个用户交给A君维护,得到的收入归A君所有. 同时,由于项目从开始到盈利有很长一段时间(我从去年10月开始开发,到今年4月扭亏为盈,花了半年时间达到盈利).既然已经盈利,A君再承担这个风险并不是一个好的选择,因此提供了5W的起始资金,作为这一段时间的补偿.至于分红方式,因为新项目刚开发一周,并不知道A君能做到什么程度,因此这件事就延后了.



* 继续开发
  2个月后,A君的新软件雏形完成了,我们召集了一批测试者进行公测.这次的测试很有意思,出现了突发情况,竞争对手基本没来得及反应就死翘翘了,我因为一些偶然的原因做了充分准备,突发情况出现的时候在1分钟左右完成了版本更新,2分钟后,软件顺利部署到上万的客户端上,表现不错. 同时因为底层组件的更新, A君的新软件也更新了(因为对手全挂了- =,我们软件正常跑就算ok了).宣传变得十分容易. A君再次提出了分红的要求.

  推广渠道按照市场价需要4成的利润,而且推广是我一个要好的朋友,我无意压低他的分成.因此我提出我少分1,给我推广的朋友.考虑到新软件依旧还未盈利,我提出了2 4 4的分成方案, 推广渠道按照市场价需要4成的利润4, 我2, A君4. 目前为止,新软件开始有盈利迹象.

  这时,A君希望继续跟我讨论老软件的分红问题. 我还是坚持方案1的原则,提出:
  "应该按劳分配,而不应该将所有盈利项目混在一起,我为两个项目提供支持,因此参与两个项目的分红,A君只负责一个项目,因此只应该参与一个项目的分红.老项目分红应该在我和我的下家之间进行."

  A君认为不妥,他是合作者,不是打工仔.

  经过仔细思考,我提出了结束合作的要求.主要是基于以下3点考虑:

  1. 忙了2个月,工作量增加了不少,收入反而不如以前.这样的时间不知道会持续多长时间,是否有冒险的价值.

  2. 目前A君的项目还有很长路要走, 我只要求2的分成, 这远远小于我目前贡献.即,我的一部分精力需要投入到回报很低的地方.

  3. A君对老项目还看不出有哪部分能够提供支持,现在没有,以后可能的概率也很低,因为老项目涉及到核心部分,必须保证100% BUG FREE, A君目前的表现(计划2周的项目延期到2月,发布之时依旧出现不少BUG),需要一段较长的时间来提升技能,提前给予分红风险太大.

  4. 目前我对A君的帮助是显而易见的, A君对我正在进行的工作还没有帮助.如果因为我有一个稳定的收入来源而承担所有风险,我觉得这不是一个公平的方案.


* 结束

  最终的结果是,回归原样. 我依旧负责老软件的维护以及相关的用户群, A君继续维护新软件. 起始资金作为A君2月应有的回报, 现有代码依旧可以使用. 不过我不再继续提供更新服务.

  这或许是一个好的解决方案, 一番尝试, A君和我并没有太大的损失. A君有了自己的用户群和软件(用户群不同,我们两并不形成竞争关系). 我经历了一番有意义的思考.结束合作的那一天,我尝试性地开发了一下新软件,发现我来做这件事,或许只需要不到1周的时间(客户端主要的功能只花了1天来完成,验证和推广可能还需要一些时间),这更加坚定了我的想法.

* 思考

1. 什么是合作

   以前想,合作就是两个人干同一件事情. 但是,似乎有很多种合作. 比如这次失败的原因,我想就是我们双方对合作的认识有分歧.

   对我来说,我是强势方,因为早一步开始项目,拥有独立开发销售整个项目的能力.A君可能希望作为等价的参与者,参与整个项目,作为一个类似"股东"的角色.然而实际上,目前已经做的事情,更像如下的模式.

   "麦当劳在美国开了很多店,做的不错.提出希望在中国开店. 中国的一家企业希望合作. 麦当劳提供了资金, 宣传渠道, 实物配方, 管理经验, 中国企业负责产品本地化 ,并在全国各地开设麦当劳分店. 第一年度结账时, 宣传渠道和各店店长拿掉4成(成本), 本地企业拿4成, 麦当劳收取2成.(这时,中国麦当劳可能还是亏损状态)"

   "本地企业希望以合作者身份继续参与美国麦当劳收入(美国麦当劳已经有很好地盈利表现),麦当劳公司予以拒绝.中国公司认为,中国市场很大,几年之后也能有很好的表现. 麦当劳考虑到中国未来几年的不确定性,决定与该公司结束合作关系".

   即A君已经完成的工作,只作用于局部(新软件以及其用户群),而非作用于全局(核心部分).却希望获得全局的分成,同时希望预支以后可能的贡献(以后可能会参与核心部分,所以要整体分成).这是我不能接受的合作模式. 我希望的是局部合作,而非全局合作.事实上由于A君对业务并不熟悉,技术还有差距,并不能担任全局维护的职能.

3. 谁对谁错

   这是一直在我脑海中思考的问题. 事实上,这并没有什么争议的地方,明显问题在我自身. 因为A君只是完成我分配的任务, 虽然没有达到预期表现, 但是并没有任何和之前协商不一致的行为发生. 最后的合作结束的原因,归根结底是没有在最开始说清分红//合作模式,而是直接商定了工作内容,最后导致分歧. 而且A君在第一周结束的时候提出过这件事,我却没有好好解决这个问题,导致2个月软件上线后变得更为麻烦. 给推广的朋友也带来不少麻烦.

2. 交换角色,我会怎么做?

   2.1 创造价值,并且不侵犯既得利益

   因为并非从一开始从零做起,而是半路加入. 我想一个原则是不侵犯原参与者的[既得利益]. 人对于现有物品减少的敏感程度远远大于多得到的部分的减少. 如果我加入一个团队, 我会尽可能为团队产生价值. 新价值的产生包含了我的个人努力和团队支持,类似生成资料和劳动力的关系. 这部分价值, 我会争取我应得的部分, 并且也是比较容易争取的部分.

   2.2 尽早协商

   我在团队中发挥的作用越来越大,产生的价值也会越来越多. 之前的工资/分红或许已经不能满足现在的需要.我需要在价值产生之前(并且所有人都[可预见],而不是持怀疑态度),尽早提出增加薪水/分红的要求.并提出合理的原因.

   如:某老板准备加大3倍投资,在投资前提出,投资后希望增加5%分红的要求.而不是在投资后提出.

   反例:某老板说准备明年追加很大投资,希望现在增加5%分红.
